bump to bazel version 6 + docs
chainguard-images/images pull request #148
Opened 2022-12-22 19:29 UTC by rawlingsj

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>

2022-12-22 20:22 UTC, luhring approved these changes

2022-12-23 15:02 UTC, jdolitsky requested changes
wait! need to change the `extractTagsFrom` field: https://github.com/chainguard-images/images/blob/main/images/bazel/image.yaml#L6

2022-12-23 23:19 UTC, rawlingsj commented
great spot! doing that now..

2022-12-24 00:07 UTC, dlorenc approved these changes

2022-12-24 00:16 UTC, luhring approved these changes

2022-12-28 16:29 UTC, jdolitsky approved these changes

2022-12-28 16:29 UTC, merged