make Jenkins, Maven, JDK and JRE consistent with new template style
chainguard-images/images pull request #315
Opened 2023-03-02 16:19 UTC by rawlingsj

2023-03-02 16:39 UTC, ltagliaferri requested changes
One nit —  a link needs an update or a change to the header, thank you!

2023-03-02 16:39 UTC, ltagliaferri commented on images/jenkins/README.md
> +- [Getting Started Guide](https://edu.chainguard.dev/chainguard/chainguard-images/reference/jenkins/overview/#use-it)
No use-it header here

```suggestion
- [Getting Started Guide](https://edu.chainguard.dev/chainguard/chainguard-images/reference/jenkins/overview/#usage)
```

2023-03-02 16:39 UTC, ltagliaferri commented on images/jenkins/README.md
> +- [Getting Started Guide](https://edu.chainguard.dev/chainguard/chainguard-images/reference/jenkins/overview/#use-it)
Alternately can change the `Usage` header to `Use it`

2023-03-02 18:07 UTC, ltagliaferri approved these changes

2023-03-08 01:42 UTC, luhring approved these changes

2023-03-08 01:42 UTC, merged