Bring nginx closer to Docker official image.
chainguard-images/images pull request #478
Opened 2023-04-19 09:58 UTC by amouat

*THIS INCLUDES BREAKING CHANGES*

Most notably default port is now 8080 rather than 80, but also other config changes including default html directory and auto determining how many worker processes to instantiate.

This is all referenced in the README, which also includes information on how to get the old version. Is this enough or do we need to handle this differently?

Fixes: #452 #382

2023-04-19 11:25 UTC, patflynn commented
This looks great.  @eddiezane @kaniini for approval.  

Let's quickly discuss offline the consequence of the breaking change.

2023-04-19 14:50 UTC, amdawson commented
OK I guess let's go for it

2023-04-19 14:51 UTC, amdawson approved these changes

2023-04-20 02:09 UTC, mathieu-benoit commented
Wow, thank you for the hard work on this @amouat! Looking forward to testing it!

Out of curiosity, is it fixing https://github.com/chainguard-images/images/issues/288 too?

2023-05-03 09:58 UTC, amouat commented
I have now made a mess of the git history somehow :sob:

2023-05-03 11:41 UTC, amouat commented
Now a test is failing :sob:

2023-05-03 16:12 UTC, imjasonh requested changes

2023-05-03 16:12 UTC, imjasonh commented on images/nginx/README.md
> +On May 3 2023 the Chainguard nginx image was rebuilt with several improvements, including
Can you link an issue/PR to describe why this change was made, or what kinds of changes were made?

2023-05-03 16:12 UTC, imjasonh commented on images/nginx/README.md
>  The changes include:
```suggestion
The changes included:
```

2023-05-03 16:12 UTC, imjasonh commented on images/nginx/README.md
> +image strives for minimalism and the default image does not include a shell or pacakge manager,
```suggestion
image strives for minimalism and the default image does not include a shell or package manager,
```

2023-05-03 16:12 UTC, imjasonh commented on images/nginx/README.md
> +## Differences to Docker Official Image
```suggestion
## Differences to [Docker Official Image](https://hub.docker.com/_/nginx)
```

2023-05-04 10:41 UTC, imjasonh approved these changes

2023-05-04 10:41 UTC, merged